name: Test and Deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3 # actions uses, commands run
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test # running sequential -> takes longer
    runs-on: ubuntu-latest
    steps:
      - name: (Debug) List Repository Contents
        run: ls -a
      - name: Build Project
        run: npm run build
      - name: Deploy Project to Host
        run: echo "Deploying...."
